name: Rust Check and Bloat

on:
  schedule:
    - cron: "0 0 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run cargo check to check dependencies
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo bloat analysis
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
